name: nas_cp
channels:
  - pytorch
  - conda-forge
  - nodefaults

dependencies:
  - python~=3.10.0
  - pydantic~=2.10
  - pandas~=2.2
  - numpy~=1.26  # 1.24 seems to cause this issue: https://github.com/numba/numba/issues/8615
  - matplotlib~=3.1, <3.6
  - seaborn
  - scikit-learn==1.4.0
  - typer~=0.4
  - tqdm~=4.64.1
  - ipywidgets~=8.0.4
  - scipy~=1.11
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - termcolor
    - fvcore
    - dill
